title: Ondeando
description: meu proto-jardim-digital, um espaço para ficar mais distante das mídias-sociais, feeds infinitos e algorítmos malvados.
url: "https://pedro.dalbo.me"
author: dalbo1201
kramdown:
  hard_wrap: true
highlighter: rouge
future: false
timezone: America/Sao_Paulo

# --- COLLECTIONS ---
collections:
  blog:
    output: true
  fotolog:
    output: true
  microblog:
    output: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2

pagination:
  enabled: true

feed:
  collections:
    - blog
    - fotolog
    - microblog

# --- DEFAULTS ---
defaults:
  - scope:
      path: ""
      type: blog
    values:
      layout: post
      permalink: /blog/:slug/

  - scope:
      path: ""
      type: fotolog
    values:
      layout: foto
      permalink: /fotolog/:slug/

  - scope:
      path: ""
      type: microblog
    values:
      layout: microblog-post
      permalink: /microblog/:year-:month-:day/

exclude:
  - README.md
  - LICENSE.md