title: Ondeando
description: meu proto-jardim-digital, um espaço para ficar mais distante das mídias-sociais, feeds infinitos e algorítmos malvados.
url: "https://pedro.dalbo.me"
author: dalbo1201
image: /assets/og_image/og-default.png
blog_image: /assets/og_image/og-image-blog.png
fotolog_image: /assets/og_image/og-image-fotolog.png
fediverse_creator: "@dalbo1201@mastodon.social"
kramdown:
  hard_wrap: true
highlighter: rouge
future: false
timezone: America/Sao_Paulo

# --- COLLECTIONS ---
collections:
  blog:
    output: true
  fotolog:
    output: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2

pagination:
  enabled: true

feed:
  collections:
    - blog
    - fotolog

# --- DEFAULTS ---
defaults:
  - scope:
      path: ""
      type: blog
    values:
      layout: post
      permalink: /blog/:slug/

  - scope:
      path: ""
      type: fotolog
    values:
      layout: foto
      permalink: /fotolog/:slug/

exclude:
  - README.md
  - LICENSE.md
