source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
gem 'jekyll-paginate'
gem "minima", "~> 2.5.1"
gem "jekyll-sass-converter", "~> 2.2.0"
gem "csv"
gem "base64"
gem "bigdecimal"
gem "webrick", "~> 1.7"
gem "wdm", ">= 0.1.0" if Gem.win_platform?
gem 'jekyll-feed'
gem "bundler", "~> 2.1"

